# Generated by Django 4.2.3 on 2023-07-29 09:57

from django.db import migrations, models
import web_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('ID', models.CharField(default=web_app.models.generate_unique_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
