# Generated by Django 4.2.3 on 2023-07-30 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_mymodel_reg_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_data',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reg_data',
            name='salary_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
