# Generated by Django 4.2.3 on 2023-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_reg_data_salary_reg_data_salary_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_data',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='reg_data',
            name='salary_updated_date',
        ),
    ]
