# Generated by Django 4.2.3 on 2023-07-30 06:48

from django.db import migrations, models
import django.utils.timezone
import web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_remove_reg_data_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('ID', models.CharField(default=web_app.models.generate_unique_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_updated_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
