# Generated by Django 4.2.3 on 2023-07-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Salary',
        ),
    ]
