# Generated by Django 4.2.3 on 2023-07-30 08:33

from django.db import migrations, models
import web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_rename_mymodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_data',
            name='ID',
            field=models.CharField(default=web_app.models.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
