# Generated by Django 4.2.3 on 2023-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_reg_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_data',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
