# Generated by Django 4.2.3 on 2023-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_alter_reg_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_data',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
