# Generated by Django 4.2.3 on 2023-08-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_reg_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_data',
            name='img',
            field=models.ImageField(default='/storage/emulated/0/Download/Tt/django_proj/web_db/static/images/davatar.png', upload_to='upload/'),
        ),
    ]
