# Generated by Django 4.2.3 on 2023-08-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_alter_reg_data_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-salary_updated_date']},
        ),
    ]
