# Generated by Django 4.2.3 on 2023-08-06 07:20

from django.db import migrations, models
import web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0014_alter_salary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='ID',
            field=models.CharField(default=web_app.models.generate_unique_id, max_length=36, primary_key=True, serialize=False),
        ),
    ]
