# Generated by Django 4.2.3 on 2023-08-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0015_alter_salary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='ID',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
